# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ikuklina <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/05 21:08:04 by ikuklina          #+#    #+#              #
#    Updated: 2019/11/06 17:57:19 by ikuklina         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do_op

SRC = do_op.c

OUT = do-op

all:
	gcc -w -w -w $(SRC) -o $(OUT)

clean:
	/bin/rm -f $(OUT)

fclean: clean
	/bin/rm -f $(OUT)

re: fclean all
